<?php
/**
 * OntoWiki rdf upload import import template
 */
$translate = OntoWiki::getInstance()->translate;
?>
<fieldset class="activeForm" id="importdata">
    <legend><?php echo $this->_($translate->translate('Upload list of titles from CSV file')) ?></legend>
    <div class="width49 float margin">
        <div>
            <p class="messagebox info"><?php echo $translate->translate('Please select if the titles should belong to a license package or should be attached to the annual contract data directly.') ?></p>
            <label for="package" class="checkboxradio"><?php echo $translate->translate('New license package') ?>
                <input type="radio" class="radio" name="collectIn" id="package" value="package" />
            </label>
            <label for="contract" class="checkboxradio"><?php echo $translate->translate('New annual contract data') ?>
                <input type="radio" class="radio" name="collectIn" id="contract" value="contract" checked="checked" />
            </label>
            <br class="clearall"/>
            <br class="clearall"/>
            <label for="label-input"><?php echo $this->_('Label for contract/package information') ?></label>
            <input type="text" class="text" id="label-input" name="resourcelabel" />
            <br class="clearall"/>
            <br class="clearall"/>
            <p class="messagebox info"><?php echo $this->_('Please search for an existent resource that should contain the contract items.') ?></p>
            <div class="contracts-data">
                <input  id="contracts-input" class="typeahead width67" type="text" value="" name="contracts-input"/>
            </div>
        </div>
        <div>
            <p class="messagebox info">
                <?php $msg = 'Please select a UTF-8 encoded CSV File to import.' ?>
                <?php $msg.= ' Expected order of columns will be: Title, ISBN/ISSN (print),' ?>
                <?php $msg.= ' ISBN/ISSN (electronic), Proprietary-ID, DOI, price (without' ?>
                <?php $msg.= ' thousands seperator)' ?>
                <?php echo $this->_($translate->translate($msg)) ?>
            </p>
            <p class="messagebox info">
                <?php $msg = 'A title is necessary. Furthermore at least one identifier or,' ?>
                <?php $msg.= ' in case of media without any identifiers, "NA" has to be' ?>
                <?php $msg.= ' entered into each id column.' ?>
                <?php echo $this->_($translate->translate($msg)) ?>
            </p>
        </div>
        <div>
            <label for="file-input">
                <?php echo sprintf(
                    $this->_('File (max. %1$sB)'),
                    preg_replace('/([kMG])/', ' $1', ini_get('upload_max_filesize'))
                ) ?>
            </label>
            <input type="file" id="file-input" name="source" />
            <br class="clearall" />
            <br class="clearall"/>
            <label for="label-input"><?php echo $this->_('Validity year') ?></label>
            <input type="text" class="text" size="4" maxlength="4" value='<?php echo date("Y")+1 ?>' id="year-input" name="validityyear" />
            <br class="clearall"/>
        </br>
            <p class="messagebox info"><?php echo $this->_('CSV import settings') ?></p>
            <label for="hasTitle"><?php echo $this->_($translate->translate('CSV contains title row')) ?></label>
            <input type="checkbox" checked id="hasTitle" name="title" />
            <br class="clearall"/>
            <label for="delimiter-input"><?php echo $this->_($translate->translate('Field delimiter')) ?></label>
            <input type="text" class="text" size="1" maxlength="1" value=";" class="text" id="delimiter-input" name="delimiter" />
            <br class="clearall"/>
            <label for="enclosure-input"><?php echo $this->_($translate->translate('Field enclosure')) ?></label>
            <input type="text" class="text" size="1" maxlength="1" value='"' id="enclosure-input" name="enclosure" />
            <br class="clearall"/>
        </div>
    </div>
</fieldset>
